[package]
name = "qb-control"
version.workspace = true
edition.workspace = true

[dependencies]
bitcode = "0.6.0"
serde = { version = "1.0.204", features = ["derive"] }
simdutf8 = "0.1.4"
qb-core = { path = "../qb-core" }
# qbi-rtc = { path = "../qbi-rtc" }
qbi-local = { path = "../qbi-local" }
