[package]
name = "qbi-rtc"
version.workspace = true
edition.workspace = true

[dependencies]
qb = { path = "../qb" }
qb-derive = { path = "../qb-derive" }
tokio = { version = "1.37.0", features = ["rt", "sync"] }
webrtc = "0.11.0"
