[package]
name = "qb-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.37.0", features = ["rt", "sync"] }
# qbi-rtc = { path = "../qbi-rtc" }
qbi-local = { path = "../qbi-local" }
qb-core = { path = "../qb-core" }
tracing-subscriber = "0.3.18"
tracing-panic = "0.1.2"
