[package]
name = "rust_lib_qb_mobile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.3.0"
qb-daemon = { path = "../../qb-daemon" }
qb-core = { path = "../../qb-core" }
lazy_static = "1.5.0"
