[package]
name = "qb-cli"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.37.0", features = ["rt", "sync"] }
interprocess = { version = "2.2.0", features = ["tokio"] }
