name: Lint code

on: 
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  clippy:
    name: Check for clippy warnings
    runs-on: ubuntu-latest
    env:
      RUSTGLAGS: '-D warnings'
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --verbose
