name: Deploy sites

on: 
  push:
    branches:
      - main
    paths:
      - 'sites/*/**'

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  quixbyte_org:
    name: Build sites/quixbyte.org
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sites/quixbyte.org
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: quixbyte_org
          path: sites/quixbyte.org/build

  publish:
    name: Publish to github pages
    needs: quixbyte_org
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: quixbyte_org
          path: ./quixbyte_org
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './quixbyte_org'
      - uses: actions/deploy-pages@v1
